In [15]:
import pandas as pd

In [16]:
import numpy as np

In [17]:
data = {
    'Uzbekistan' : {2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan' : {2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}

In [18]:
df = pd.DataFrame(data)

In [19]:
df

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [20]:
usernames = {'anvar':'anvarbeks223', 'olim':'olimtoy', 'maryam':'maryam334455', 'javohir':'javohir445'}
emails = {'anvar':'anvar@gmail.com', 'olim':'olim@mail.ru', 'maryam':'mary33@gmail.com', 'javohir':'javohir445@gmail.com'}

data = {
    'username' : usernames,
    'email' : emails
}

In [21]:
df = pd.DataFrame(data)

In [22]:
df

             username                 email
anvar    anvarbeks223       anvar@gmail.com
olim          olimtoy          olim@mail.ru
maryam   maryam334455      mary33@gmail.com
javohir    javohir445  javohir445@gmail.com

In [23]:
df.index

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')

In [24]:
data2 = {
    'username':{'olim':'olimjon21', 'maryam':'maryam2020'},
    'email':{'olim':'olimjon21@gmail.com', 'maryam':'maryam2020@mail.ru'}
}

In [28]:
df2 = pd.concat([df, pd.DataFrame(data2)]) # eski append metodi
df2

             username                 email
anvar    anvarbeks223       anvar@gmail.com
olim          olimtoy          olim@mail.ru
maryam   maryam334455      mary33@gmail.com
javohir    javohir445  javohir445@gmail.com
olim        olimjon21   olimjon21@gmail.com
maryam     maryam2020    maryam2020@mail.ru

In [34]:
newind = pd.Index(['olim', 'nafisa', 'hamida'])

In [35]:
newind

Index(['olim', 'nafisa', 'hamida'], dtype='object')

In [37]:
newind.isin(df2.index) #newind qiymatlari df2 indeksi ichida bor yo'qligini tekshiradi

array([ True, False, False])

In [40]:
df2.index.difference(newind) #df2 hamda newind indekslari o'rtasidafi farqli qiymatlarni qaytaradi

Index(['anvar', 'javohir', 'maryam'], dtype='object')

In [41]:
newind.difference(df2.index)

Index(['hamida', 'nafisa'], dtype='object')

In [42]:
df2.index.union(newind)

Index(['anvar', 'hamida', 'javohir', 'maryam', 'maryam', 'nafisa', 'olim',
       'olim'],
      dtype='object')

In [43]:
df2

             username                 email
anvar    anvarbeks223       anvar@gmail.com
olim          olimtoy          olim@mail.ru
maryam   maryam334455      mary33@gmail.com
javohir    javohir445  javohir445@gmail.com
olim        olimjon21   olimjon21@gmail.com
maryam     maryam2020    maryam2020@mail.ru

In [47]:
df2.index.delete(0)

Index(['olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [48]:
newind

Index(['olim', 'nafisa', 'hamida'], dtype='object')

In [52]:
newind.drop('nafisa')

Index(['olim', 'hamida'], dtype='object')

In [56]:
df2.index.insert(2,'masha') #indeks raqamiga ko'ra yangi indeks qo'shish

Index(['anvar', 'olim', 'masha', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [57]:
df2

             username                 email
anvar    anvarbeks223       anvar@gmail.com
olim          olimtoy          olim@mail.ru
maryam   maryam334455      mary33@gmail.com
javohir    javohir445  javohir445@gmail.com
olim        olimjon21   olimjon21@gmail.com
maryam     maryam2020    maryam2020@mail.ru

In [61]:
df2.index.is_monotonic_increasing # alifbo tartibidami yoki yoq tekshiradi

False

In [62]:
newind

Index(['olim', 'nafisa', 'hamida'], dtype='object')

In [64]:
newind.is_unique # har xil qiymatlarmi yoki bir xil tekshiradi

True

In [67]:
df2.index.unique() #takrorlanmas qiymatlarni qaytaradi yoki faqat birinchi takrorlangan qiymatni

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')